default_agent: myclaimvalidation_agent
agents:
  aws_claimvalidation_assistant:
    name: aws_claimvalidation_assistant
    language: python
    node_version: null
    entrypoint: /home/ec2-user/SageMaker/multi-agent-arc-example/agents/claimvalidation-agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::161615149547:role/AWSClaimsValidationAssistantBedrockAgentCoreRole-us-east-1
      execution_role_auto_create: false
      account: '161615149547'
      region: us-east-1
      ecr_repository: 161615149547.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-aws_claimvalidation_assistant
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: aws_claimvalidation_assistant-WZDiZzFJDt
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:161615149547:runtime/aws_claimvalidation_assistant-WZDiZzFJDt
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-aws_claimvalidation_assistant-builder
      execution_role: arn:aws:iam::161615149547:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-1db4e090aa
      source_bucket: bedrock-agentcore-codebuild-sources-161615149547-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - mo1olvm6laddjcb4stdq7sdv6
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_QFkXgIx3L/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  rag_claim_validation:
    name: rag_claim_validation
    language: python
    node_version: null
    entrypoint: /home/ec2-user/SageMaker/multi-agent-arc-example/agents/rag-agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::161615149547:role/AWSClaimsRagAssistantBedrockAgentCoreRole-us-east-1
      execution_role_auto_create: false
      account: '161615149547'
      region: us-east-1
      ecr_repository: 161615149547.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-rag_claim_validation
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: rag_claim_validation-YYjUfHDo20
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:161615149547:runtime/rag_claim_validation-YYjUfHDo20
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-rag_claim_validation-builder
      execution_role: arn:aws:iam::161615149547:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-1fb2c4b09d
      source_bucket: bedrock-agentcore-codebuild-sources-161615149547-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 2mkuhegfsf687mno7b0hrr0oco
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_r3rQMIKjN/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  aws_legal_opinion_validation_assistant:
    name: aws_legal_opinion_validation_assistant
    language: python
    node_version: null
    entrypoint: /home/ec2-user/SageMaker/multi-agent-arc-example/agents/legal-opinion-triage-validation-agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::161615149547:role/AWSLegalValidationAssistantBedrockAgentCoreRole-us-east-1
      execution_role_auto_create: false
      account: '161615149547'
      region: us-east-1
      ecr_repository: 161615149547.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-aws_legal_opinion_validation_assistant
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: aws_legal_opinion_validation_assistant-JFpQBRCxqN
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:161615149547:runtime/aws_legal_opinion_validation_assistant-JFpQBRCxqN
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-aws_legal_opinion_validation_assistant-builder
      execution_role: arn:aws:iam::161615149547:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-f63851b64e
      source_bucket: bedrock-agentcore-codebuild-sources-161615149547-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - leov6trgrlbkpsvtt5g7smm0t
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_pG5tZlIXy/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  aws_legal_triage:
    name: aws_legal_triage
    language: python
    node_version: null
    entrypoint: /home/ec2-user/SageMaker/multi-agent-arc-example/agents/triage-agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::161615149547:role/AWSClaimsValidationAssistantBedrockAgentCoreRole-us-east-1
      execution_role_auto_create: false
      account: '161615149547'
      region: us-east-1
      ecr_repository: 161615149547.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-aws_legal_triage
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: aws_legal_triage-l7B8Z65tS5
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:161615149547:runtime/aws_legal_triage-l7B8Z65tS5
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-aws_legal_triage-builder
      execution_role: arn:aws:iam::161615149547:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-b361a9f5ee
      source_bucket: bedrock-agentcore-codebuild-sources-161615149547-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 1m2dej9j10v39aml3tcabdpl3t
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_JnnzjXKFq/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  myclaimvalidation_agent:
    name: myclaimvalidation_agent
    language: python
    node_version: null
    entrypoint: /home/ec2-user/SageMaker/multi-agent-arc-example/agents/claimvalidation-agent-noAtoA.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::161615149547:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-f2404ea203
      execution_role_auto_create: false
      account: '161615149547'
      region: us-east-1
      ecr_repository: 161615149547.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-myclaimvalidation_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: myclaimvalidation_agent-qixKSjEH56
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:161615149547:runtime/myclaimvalidation_agent-qixKSjEH56
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-myclaimvalidation_agent-builder
      execution_role: arn:aws:iam::161615149547:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-f2404ea203
      source_bucket: bedrock-agentcore-codebuild-sources-161615149547-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
