default_agent: aws_appraisal_assistant
agents:
  aws_appraisal_assistant:
    name: aws_appraisal_assistant
    entrypoint: /home/sagemaker-user/Multi-Agent-Collaboration/hackathon_ClaimsAdjudication/agents/appraisal-agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::161615149547:role/AWSDocsAssistantBedrockAgentCoreRole-us-east-1
      execution_role_auto_create: false
      account: '161615149547'
      region: us-east-1
      ecr_repository: 161615149547.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-aws_appraisal_assistant
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: aws_appraisal_assistant-vUe2p2FZfq
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:161615149547:runtime/aws_appraisal_assistant-vUe2p2FZfq
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-aws_appraisal_assistant-builder
      execution_role: arn:aws:iam::161615149547:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-09b58e53de
      source_bucket: bedrock-agentcore-codebuild-sources-161615149547-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: aws_appraisal_assistant_mem-mbe9Un7lF8
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:161615149547:memory/aws_appraisal_assistant_mem-mbe9Un7lF8
      memory_name: aws_appraisal_assistant_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: true
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 1lvtmj74pvs7oa07u3abe4cg4p
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_3yiuuvNmy/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
